### ISSUE TITLE
re2/doc/xkcd.png license prohibts a commercial use

### ISSUE THREAD

**Issue by ppisar** [dgl/re-engine-RE2#12]
I noticed that re-engine-RE2-0.17 includes re2/doc/xkcd.png file which comes from <https://xkcd.com/208/> whose license is <https://creativecommons.org/licenses/by-nc/2.5/> which prohibits a commercial use. That's prevents from redistributing re-engine-RE2-0.17 in Fedora Linux distribution.

Could you please remove that image from the next release, or negotiate a more free license <https://docs.fedoraproject.org/en-US/legal/allowed-licenses/> with XKDC author?

**Comment by dgl** [comment]
It's just a copy of upstream RE2, so I've deleted it to match what they did.
